fix nix-prefetch-tree cleanup

diff --git a/bin/nix-prefetch-tree b/bin/nix-prefetch-tree
--- a/bin/nix-prefetch-tree
+++ b/bin/nix-prefetch-tree
@@ -52,25 +52,23 @@ done
 # Cleanup Routine
 
 _es=0;
-trap '
-_es="$?";
-if test "$_es" -ne 0; then
-  echo "ERROR: $_ ($_es)" >&2;
-fi
-cd -;
-rm -rf "$TDIR";
-exit "$_es";
-' HUP TERM INT QUIT;
+cleanup() {
+  if test "$_es" -ne 0; then
+    echo "ERROR: $_ ($_es)" >&2;
+  fi
+  popd > /dev/null;
+  rm -rf "$TDIR";
+  exit "$_es";
+}
 
-
-# ---------------------------------------------------------------------------- #
+trap 'export _es="$?"; cleanup;' HUP TERM INT QUIT ABRT;
 
 
 # ---------------------------------------------------------------------------- #
 
 # Make a phony `flake.nix'.
 
-cd "$TDIR";
+pushd "$TDIR" > /dev/null;
 gen_flake() {
 {
   cat <<EOF
@@ -124,6 +122,8 @@ if test "$TYPE" = tarball && test -n "${FALLBACK_TO_FILE:+y}"; then
 else
   lookup_logged;
 fi
+
+cleanup;
 
 
 # ---------------------------------------------------------------------------- #
